# Generated by Django 2.2.6 on 2019-10-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ht', models.BooleanField(default=False, verbose_name='ХД')),
                ('it', models.BooleanField(default=False, verbose_name='ИД')),
                ('mpd', models.BooleanField(default=False, verbose_name='МПД')),
                ('elf', models.BooleanField(default=False, verbose_name='ELF')),
                ('vasimr', models.BooleanField(default=False, verbose_name='VASIMR')),
                ('feep', models.BooleanField(default=False, verbose_name='FEEP')),
                ('hollow_cath', models.BooleanField(default=False, verbose_name='Полые катоды')),
                ('other_cath', models.BooleanField(default=False, verbose_name='Прочие катоды')),
                ('missions', models.BooleanField(default=False, verbose_name='Миссии')),
                ('other_thrusters', models.BooleanField(default=False, verbose_name='Прочие двигатели')),
                ('thrusters_cluster', models.BooleanField(default=False, verbose_name='Двигательные модули')),
                ('modeling', models.BooleanField(default=False, verbose_name='Моделирование')),
                ('experiment', models.BooleanField(default=False, verbose_name='Эксперимент')),
                ('theory', models.BooleanField(default=False, verbose_name='Теория')),
                ('hydrodynamics', models.BooleanField(default=False, verbose_name='Гидродинамика')),
                ('kinetics', models.BooleanField(default=False, verbose_name='Кинетика')),
                ('hybrid', models.BooleanField(default=False, verbose_name='Гибрид')),
                ('lif_diagnostics', models.BooleanField(default=False, verbose_name='LIF-диагностика')),
                ('probe_measure', models.BooleanField(default=False, verbose_name='Зондовые измерения')),
                ('ionization_oscillations', models.BooleanField(default=False, verbose_name='Ионизационные колебания')),
                ('transient_mode', models.BooleanField(default=False, verbose_name='Пролётные колебания')),
                ('high_frequency_mode', models.BooleanField(default=False, verbose_name='Высокочастотные колебания')),
                ('anomalous_mobility', models.BooleanField(default=False, verbose_name='Аномальный транспорт')),
                ('instabilities', models.BooleanField(default=False, verbose_name='Неустойчивости')),
                ('magnetic_shielding', models.BooleanField(default=False, verbose_name='Магнитное экранирование')),
                ('alternative_propellants', models.BooleanField(default=False, verbose_name='Альтернативные рабочие тела')),
                ('crossection', models.BooleanField(default=False, verbose_name='Сечения реакций')),
                ('bell_spike_mode', models.BooleanField(default=False, verbose_name='Колокол\\спица\\ласточка')),
                ('wear_test', models.BooleanField(default=False, verbose_name='Ресурсные испытания')),
                ('materials', models.BooleanField(default=False, verbose_name='Materials')),
                ('discharge_chamber', models.BooleanField(default=False, verbose_name='ГРК')),
                ('ion_optics', models.BooleanField(default=False, verbose_name='Ионная оптика')),
                ('distrib_function', models.BooleanField(default=False, verbose_name='Функция распределения')),
                ('second_electron_emission', models.BooleanField(default=False, verbose_name='Вторичная электронная эмиссия')),
                ('ecdi', models.BooleanField(default=False, verbose_name='Эл.-цикл. дрейф. неустойчивость')),
                ('edi', models.BooleanField(default=False, verbose_name='Эл. дрейф. неустойчивость')),
                ('two_stream_instability', models.BooleanField(default=False, verbose_name='Двухпотоковая неустойчивость')),
                ('gdi', models.BooleanField(default=False, verbose_name='Градиентно-дрейфовая неустойчивость')),
                ('ion_sound', models.BooleanField(default=False, verbose_name='Ионно-звуковая неустойчивость')),
            ],
        ),
    ]
