# Generated by Django 2.2.6 on 2019-11-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='disk_space_link',
            field=models.FileField(upload_to='uploads/pdf', verbose_name='Ссылка на дисковое пространство'),
        ),
    ]
