# Generated by Django 2.2.6 on 2019-10-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_001', models.TextField(blank=True, max_length=64, verbose_name='Автор 1')),
                ('author_002', models.TextField(blank=True, max_length=64, verbose_name='Автор 2')),
                ('author_003', models.TextField(blank=True, max_length=64, verbose_name='Автор 3')),
                ('author_004', models.TextField(blank=True, max_length=64, verbose_name='Автор 4')),
                ('author_005', models.TextField(blank=True, max_length=64, verbose_name='Автор 5')),
                ('author_006', models.TextField(blank=True, max_length=64, verbose_name='Автор 6')),
                ('author_007', models.TextField(blank=True, max_length=64, verbose_name='Автор 7')),
                ('author_008', models.TextField(blank=True, max_length=64, verbose_name='Автор 8')),
                ('author_009', models.TextField(blank=True, max_length=64, verbose_name='Автор 9')),
                ('author_010', models.TextField(blank=True, max_length=64, verbose_name='Автор 10')),
            ],
        ),
    ]
