# Generated by Django 2.2.6 on 2019-10-23 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название статьи')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год написания')),
                ('doi', models.CharField(max_length=64, unique=True)),
                ('abstract', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Abstract')),
                ('disk_space_link', models.CharField(max_length=255, unique=True, verbose_name='Ссылка на дисковое пространство')),
                ('ours', models.BooleanField(verbose_name='Публикация KeRC')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата добавления')),
                ('author_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraryapp.Authors')),
                ('reference_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraryapp.References')),
                ('source_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraryapp.Sources')),
                ('theme_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraryapp.Themes')),
            ],
        ),
    ]
