# Generated by Django 2.2.6 on 2019-11-13 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraryapp', '0002_auto_20191107_1128'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='время')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Полка',
                'verbose_name_plural': 'Полки',
                'unique_together': {('user', 'article')},
            },
        ),
    ]
